version: "3.8"

services:
  workspace:
    build:
      context: ./workspace
      dockerfile: Dockerfile
      args:
        PROTO_VERSION: 0.41.3
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: host
    extra_hosts:
      - host.docker.internal:host-gateway
